<?php

namespace App\Enums;

enum AppDenyReason: string
{
    case UNAUTHENTICATED = 'UNAUTHENTICATED';
    case CSRF_INVALID = 'CSRF_INVALID';
    case NO_ACTIVE_CLIENT = 'NO_ACTIVE_CLIENT';
    case NOT_A_CLIENT_MEMBER = 'NOT_A_CLIENT_MEMBER';
    case INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE';
    case PLATFORM_ROLE_REQUIRED = 'PLATFORM_ROLE_REQUIRED';
    case EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED';
    case EMAIL_TAKEN = 'EMAIL_TAKEN';
    case VERIFY_LINK_INVALID = 'VERIFY_LINK_INVALID';
    case VERIFY_LINK_EXPIRED = 'VERIFY_LINK_EXPIRED';
    case RATE_LIMITED = 'RATE_LIMITED';
    case INVITE_INVALID = 'INVITE_INVALID';
    case INVITE_ACCEPTED = 'INVITE_ACCEPTED';
    case INVITE_EXPIRED = 'INVITE_EXPIRED';
    case INVITE_REVOKED = 'INVITE_REVOKED';
    case ALREADY_MEMBER = 'ALREADY_MEMBER';
    case IMPORT_RUNNING = 'IMPORT_RUNNING';
    case INVALID_IMPORT_STATE = 'INVALID_IMPORT_STATE';
    case IMPORT_FILE_MISSING = 'IMPORT_FILE_MISSING';
    case IMPORT_MAPPING_INVALID = 'IMPORT_MAPPING_INVALID';
}
