<?php

namespace App\Enums;

enum AppDenyReason: string
{
    case UNAUTHENTICATED = 'UNAUTHENTICATED';
    case CSRF_INVALID = 'CSRF_INVALID';
    case NO_ACTIVE_CLIENT = 'NO_ACTIVE_CLIENT';
    case NOT_A_CLIENT_MEMBER = 'NOT_A_CLIENT_MEMBER';
    case INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE';
    case PLATFORM_ROLE_REQUIRED = 'PLATFORM_ROLE_REQUIRED';
    case IMPORT_RUNNING = 'IMPORT_RUNNING';
    case INVALID_IMPORT_STATE = 'INVALID_IMPORT_STATE';
    case IMPORT_FILE_MISSING = 'IMPORT_FILE_MISSING';
    case IMPORT_MAPPING_INVALID = 'IMPORT_MAPPING_INVALID';
}
